version: "3"

services:
  kolmafia:
    image: matschr/kolmafia:latest
    container_name: kolmafia
    restart: unless-stopped
    ports:
      - "6080:6080"
      - "60080:60080"
    volumes:
      - /home/mats/docker/files/.kolmafia:/home/kolmafia/.kolmafia
    networks:
      - docker

networks:
  docker:
    driver: bridge
